import { ProgressBar } from "progress_bar.slint";
import { TrackButtons } from "track_buttons.slint";
import { VolumeBar } from "volume_bar.slint";
import { TrackPlayingInfo } from "track_playing_info.slint";

export component NowPlayingBar {
    in property <int> current-position: 0;
    in property <int> total-duration: 0;
    callback seek-requested(int);

    callback play-paused-clicked();
    callback next-track-clicked();
    callback prev-track-clicked();
    callback shuffle-clicked();
    callback repeat-clicked();

    callback volume-changed(float);

    in property <string> current-track-title: "No song playing";
    in property <string> current-artist: "---";
    in property <image> current-art;

    in property <float> current-volume;

    in property <color> bg-color;

    in property <color> now-playing-song-text-color;
    in property <color> now-playing-artist-text-color;
    in property <int> now-playing-song-text-size;
    in property <int> now-playing-artist-text-size;

    Rectangle {
        height: 80px;
        background: root.bg-color;

        HorizontalLayout {
            spacing: 10px;

            TrackPlayingInfo {
                horizontal-stretch: 1;
                min-width: 0px;
                preferred-width: 0px;

                current-track-title: root.current-track-title;
                current-artist: root.current-artist;
                current-art: root.current-art;

                now-playing-song-text-color: root.now-playing-song-text-color;
                now-playing-artist-text-color: root.now-playing-artist-text-color;
                now-playing-song-text-size: root.now-playing-song-text-size;
                now-playing-artist-text-size: root.now-playing-artist-text-size;
            }

            VerticalLayout {
                horizontal-stretch: 3;
                spacing: 5px;

                HorizontalLayout {
                    alignment: center;
                    TrackButtons {
                        play-paused-clicked => { root.play-paused-clicked() }
                        next-track-clicked => { root.next-track-clicked() }
                        prev-track-clicked => { root.prev-track-clicked() }
                        shuffle-clicked => { root.shuffle-clicked() }
                        repeat-clicked => { root.repeat-clicked() }
                    }
                }

                HorizontalLayout {
                    ProgressBar {
                        horizontal-stretch: 1;
                        current-position: root.current-position;
                        total-duration: root.total-duration;
                        seek-requested(val) => { root.seek-requested(val) }
                    }
                }
            }

            VolumeBar {
                horizontal-stretch: 1;
                min-width: 0;
                preferred-width: 0;
                current-volume: root.current-volume;
                volume-changed(val) => { root.volume-changed(val) }
            }
        }
    }
}
