import { SeekSlider } from "../widgets/seek_slider.slint";

export component ProgressBar {
    in property <int> current-position: -1;
    in property <int> total-duration: -1;

    callback seek-requested(int);

    pure function format-time(total-seconds: int) -> string {
        let mins: int = total-seconds / 60;
        let secs = mod(total-seconds, 60);
        return mins + ":" + (secs < 10 ? "0" + secs : secs);
    }

    HorizontalLayout {
        spacing: 5px;
        padding-bottom: 10px;

        Text {
            text: format-time(root.current-position);
            font-size: 10px;
            vertical-alignment: center;
        }

        SeekSlider {
            horizontal-stretch: 1;
            current-position: root.current-position;
            total-duration: root.total-duration;

            seek-requested(val) => {
                root.seek-requested(val);
            }
        }

        Text {
            text: format-time(root.total-duration);
            font-size: 10px;
            vertical-alignment: center;
        }

    }
}
