import { IconButton } from "../widgets/icon_button.slint";

export component TrackButtons {
    callback play-paused-clicked();
    callback next-track-clicked();
    callback prev-track-clicked();
    callback shuffle-clicked();
    callback repeat-clicked();

    in property <bool> playing: false;

    HorizontalLayout {
        spacing: 40px;

        IconButton {
            icon-image: @image-url("../../../assets/icons/shuffle.png");
            clicked => {
                root.shuffle-clicked();
            }
        }

        IconButton {
            icon-image: @image-url("../../../assets/icons/prev.png");
            clicked => {
                root.prev-track-clicked();
            }
        }

        IconButton {
            icon-image: root.playing ? @image-url("../../../assets/icons/pause.png") : @image-url("../../../assets/icons/play.png");
            clicked => {
                root.play-paused-clicked();
            }
        }

        IconButton {
            icon-image: @image-url("../../../assets/icons/next.png");
            clicked => {
                root.next-track-clicked();
            }
        }

        IconButton {
            icon-image: @image-url("../../../assets/icons/repeat.png");
            clicked => {
                root.repeat-clicked();
            }
        }
    }
}
