import { VolumeSlider } from "../widgets/volume_slider.slint";

export component VolumeBar {
    in property <float> current-volume;
    callback volume-changed(float);

    pure function format-percentage(n: float) -> string {
        let percentage: int = n * 100;
        return percentage + "%";
    }

    HorizontalLayout {
        min-width: 0;
        padding-right: 10px;
        spacing: 5px;

        Text {
            text: format-percentage(root.current-volume);
            font-size: 10px;
            vertical-alignment: center;
        }

        VolumeSlider {
            horizontal-stretch: 1;
            current-volume: root.current-volume;
            
            volume-changed(vol) => {
                root.volume-changed(vol);
            }
        }
    }
}
