[package]
name = "orpheus"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
struct_field_names = "allow"
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"

[dependencies]
anyhow = "1.0.103"
dirs = "6.0.0"
image = "0.25.10"
lofty = "0.24.0"
mlua = { version = "0.11", features = ["lua54", "vendored" ] }
mpris-server = { version = "0.10.0", features = ["tokio"] }
rodio = { version = "0.22.2", features = ["playback", "mp3", "flac"] }
slint = "1.17.0"
tokio = { version = "1.52.3", features = ["full"] }
walkdir = "2.5.0"

[build-dependencies]
slint-build = "1.17.0"

[profile.small-binary]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
