[package]
name = "orpheus"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
dirs = "6.0.0"
lofty = "0.24.0"
mpd = "0.1.0"
rodio = { version = "0.22.2", features = ["playback", "mp3", "flac"] }
slint = "1.17.0"
tokio = { version = "1.52.3", features = ["full"] }
walkdir = "2.5.0"

[build-dependencies]
slint-build = "1.17.0"

[profile.small-binary]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
