[package]
name = "orpheus"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
mpd = "0.1.0"
reqwest = "0.13.4"
serde = "1.0.228"
slint = "1.17.0"
tokio = { version = "1.52.3", features = ["full"] }

[build-dependencies]
slint-build = "1.17.0"

[profile.small-binary]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
