export component TrackPlayingInfo {
    in property <string> current-track-title: "No song playing";
    in property <string> current-artist: "---";
    in property <image> current-art;

    in property <color> now-playing-song-text-color;
    in property <color> now-playing-artist-text-color;

    HorizontalLayout {
        spacing: 10px;

        VerticalLayout {
            alignment: center;
            padding-left: 10px;
            Image {
                source: root.current-art;
                width: 45px;
                height: 45px;
            }
        }

        VerticalLayout {
            min-width: 0;
            alignment: center;
            padding-top: 10px;
            padding-left: 10px;

            Text {
                text: root.current-track-title;
                color: now-playing-song-text-color;
                font-size: 15px;
                horizontal-alignment: left;
                overflow: elide;
            }

            Text {
                text: root.current-artist;
                color: now-playing-artist-text-color;
                font-size: 12px;
                horizontal-alignment: left;
                overflow: elide;
            }
        }
    }
}
