import { Slider } from "std-widgets.slint";

export component VolumeBar {
    callback volume-changed(float);

    pure function format-percentage(n: float) -> string {
        let percentage: int = n * 100;
        return percentage + "%";
    }

    HorizontalLayout {
        min-width: 0;
        padding-right: 10px;
        spacing: 5px;

        Text {
            text: format-percentage(slider.value);
            font-size: 10px;
            vertical-alignment: center;
        }

        slider := Slider {
            minimum: 0;
            maximum: 1;
            value: 1.0;

            changed(vol) => {
                volume-changed(vol);
            }
        }
    }
}
