import { SlintAlbum, SlintSong } from "types.slint";
import { Button, ListView } from "std-widgets.slint";

export component AlbumView {
    in property <SlintAlbum> album;

    callback back-clicked;
    callback play-album-clicked;
    callback play-track-clicked(int);

    VerticalLayout {
        padding: 20px;
        spacing: 10px;

        HorizontalLayout {
            alignment: start;
            spacing: 10px;

            VerticalLayout {
                alignment: center;
                Image {
                    source: album.art;
                    width: 80px;
                    height: 80px;
                }
            }

            VerticalLayout {
                horizontal-stretch: 0;

                Text {
                    text: root.album.title;
                    font-size: 28px;
                    font-weight: 700;
                }

                Text {
                    text: root.album.artist;
                    font-size: 18px;
                }
            }

            Button {
                text: "▶";
                width: 70px;
                height: 70px;
                clicked => {
                    root.play-album-clicked();
                }
            }

        }

        ListView {
            for entry[i] in root.album.tracks: TouchArea {
                height: 65px;
                Rectangle {
                    VerticalLayout {
                        spacing: 4px;
                        alignment: center;
                        Text { text: entry.title; font-size: 15px; }
                        Text { text: entry.artist; font-size: 12px; }
                    }
                }
                clicked => {
                    root.play-track-clicked(i);
                }   
            }
        }
    }
}
