import { Button, ListView } from "std-widgets.slint";
import { SlintAlbum, SlintSong } from "types.slint";
import { AlbumView } from "album_view.slint";
import { ProgressBar } from "progress_bar.slint";
import { VolumeBar } from "volume_bar.slint";

enum View { Library, Album }

export component AppWindow inherits Window {
    title: "orpheus";
    width: 400px;
    height: 500px;
    background: #1e1e2e;

    in property <[SlintAlbum]> albums: [];
    in-out property <View> current-view: View.Library;
    in-out property <SlintAlbum> viewing-album;
    in-out property <int> viewing-album-index;

    in property <string> current-track-title: "No song playing";
    in property <string> current-artist: "---";
    in property <int> current-position: 0;
    in property <int> total-duration: 0;

    callback play-paused-clicked();
    callback next-track-clicked();
    callback prev-track-clicked();

    callback play-album-clicked();
    callback play-track-clicked(int);

    callback seek-requested(int);
    callback volume-changed(float);

    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        alignment: center;

        Text {
            text: root.current-track-title;
            color: #cdd6f4;
            font-size: 16px;
            horizontal-alignment: center;
        }

        Text {
            text: root.current-artist;
            color: #cdd6f4;
            font-size: 16px;
            horizontal-alignment: center;
        }

        Button {
            text: "play/pause";
            clicked => {
                root.play-paused-clicked();
            }
        }

        Button {
            text: "next track";
            clicked => {
                root.next-track-clicked();
            }
        }

        Button {
            text: "previous track";
            clicked => {
                root.prev-track-clicked();
            }
        }

        ProgressBar {
            current-position: root.current-position;
            total-duration: root.total-duration;
            seek-requested(val) => { root.seek-requested(val) }
        }

        VolumeBar {
            volume-changed(val) => { root.volume-changed(val) }
        }

        if root.current-view == View.Album:
            AlbumView {
                album: root.viewing-album;
                back-clicked => { root.current-view = View.Library }
                play-album-clicked => { root.play-album-clicked() }
                play-track-clicked(idx) => { root.play-track-clicked(idx) }
            }
        
        if root.current-view == View.Library: 
            ListView {
                height: 200px;
                for entry[i] in root.albums: TouchArea {
                    height: 65px;
                    Rectangle { VerticalLayout {
                        spacing: 4px;
                        alignment: center;
                        Text { text: entry.title; font-size: 15px; }
                        Text { text: entry.artist; font-size: 12px; }
                    } }
                    clicked => {
                        root.current-view = View.Album;
                        root.viewing-album = root.albums[i];
                        root.viewing-album-index = i;
                    }
                }
            }
    }
}
