import { Button, ListView } from "std-widgets.slint";
import { SlintAlbum, SlintSong, SlintPlaylist } from "types.slint";
import { AlbumView } from "views/album_view.slint";
import { LibraryView } from "views/library_view.slint";
import { NowPlayingBar } from "now_playing/now_playing_bar.slint";
import { Sidebar } from "sidebar.slint";
import { PlaylistsView } from "views/playlists_view.slint";
import { OpenPlaylistView } from "views/open_playlist_view.slint";

import "../../assets/fonts/NotoSans-Regular.ttf";
import "../../assets/fonts/HurmitNerdFont-Regular.otf";

enum View { Library, Album, Playlists, OpenPlaylist }

export component AppWindow inherits Window {

    title: "orpheus";
    background: #1e1e2e;
    default-font-family: "Noto Sans";

    in property <[SlintAlbum]> albums: [];
    in-out property <View> current-view: View.Library;
    in-out property <SlintAlbum> viewing-album;
    in-out property <int> viewing-album-index;

    in property <string> current-track-title: "No song playing";
    in property <string> current-artist: "---";
    in property <image> current-art;
    in property <int> current-position: 0;
    in property <int> total-duration: 0;
    in property <float> current-volume;

    in property <[SlintPlaylist]> playlists: [];
    in-out property <SlintPlaylist> viewing-playlist;
    in-out property <int> viewing-playlist-index;

    forward-focus: key-handler;
    callback key_pressed_event(key: string, ctrl: bool, shift: bool, alt: bool);

    key-handler := FocusScope {
        key-pressed(event) => {
            root.key_pressed_event(
                event.text,
                event.modifiers.control,
                event.modifiers.shift,
                event.modifiers.alt,
            );
            return accept;
        }
    }

    callback play-paused-clicked();
    callback next-track-clicked();
    callback prev-track-clicked();
    callback shuffle-clicked();
    callback repeat-clicked();

    callback play-album-clicked();
    callback play-track-clicked(int);

    callback play-playlist-clicked();
    callback play-playlist-track-clicked(int);
    callback playlist-opened(int);

    callback seek-requested(int);
    callback volume-changed(float);

    // LUA CONFIG
    in property <color> sidebar-bg;
    in property <color> now-playing-bar-bg;
    in property <color> library-view-bg;
    in property <color> album-view-bg;
    in property <color> playlists-view-bg;
    in property <color> open-playlist-view-bg;

    in property <color> sidebar-text-color;
    in property <color> now-playing-song-text-color;
    in property <color> now-playing-artist-text-color;
    in property <color> detail-view-header-title-text-color;
    in property <color> detail-view-header-subtitle-text-color;
    in property <color> library-list-title-text-color;
    in property <color> library-list-subtitle-text-color;
    in property <color> album-list-title-text-color;
    in property <color> album-list-subtitle-text-color;

    in property <int> sidebar-text-size;
    in property <int> now-playing-song-text-size;
    in property <int> now-playing-artist-text-size;
    in property <int> detail-view-header-title-text-size;
    in property <int> detail-view-header-subtitle-text-size;
    in property <int> library-list-title-text-size;
    in property <int> library-list-subtitle-text-size;
    in property <int> album-list-title-text-size;
    in property <int> album-list-subtitle-text-size;

    VerticalLayout {

        HorizontalLayout {
            vertical-stretch: 1;

            Sidebar {
                library-selected => { root.current-view = View.Library }
                playlists-selected => { root.current-view = View.Playlists }
                bg-color: root.sidebar-bg;
                sidebar-text-color: root.sidebar-text-color;
                sidebar-text-size: root.sidebar-text-size;
            }

            VerticalLayout {

                if root.current-view == View.Album:
                    AlbumView {
                        album: root.viewing-album;
                        bg-color: root.album-view-bg;
                        detail-view-header-title-text-color: root.detail-view-header-title-text-color;
                        detail-view-header-subtitle-text-color: root.detail-view-header-subtitle-text-color;
                        detail-view-header-title-text-size: root.detail-view-header-title-text-size;
                        detail-view-header-subtitle-text-size: root.detail-view-header-subtitle-text-size;
                        album-list-title-text-color: root.album-list-title-text-color;
                        album-list-subtitle-text-color: root.album-list-subtitle-text-color;
                        album-list-title-text-size: root.album-list-title-text-size;
                        album-list-subtitle-text-size: root.album-list-subtitle-text-size;
                        play-album-clicked => { root.play-album-clicked() }
                        play-track-clicked(idx) => { root.play-track-clicked(idx) }
                    }
                
                if root.current-view == View.Library: 
                    LibraryView {
                        albums: root.albums;
                        bg-color: root.library-view-bg;
                        library-list-title-text-color: root.library-list-title-text-color;
                        library-list-subtitle-text-color: root.library-list-subtitle-text-color;
                        library-list-title-text-size: root.library-list-title-text-size;
                        library-list-subtitle-text-size: root.library-list-subtitle-text-size;
                        album-opened(i) => {
                            root.current-view = View.Album;
                            root.viewing-album = root.albums[i];
                            root.viewing-album-index = i;
                        }
                    }

                if root.current-view == View.OpenPlaylist:
                    OpenPlaylistView {
                        bg-color: root.open-playlist-view-bg;
                        detail-view-header-title-text-color: root.detail-view-header-title-text-color;
                        detail-view-header-subtitle-text-color: root.detail-view-header-subtitle-text-color;
                        detail-view-header-title-text-size: root.detail-view-header-title-text-size;
                        detail-view-header-subtitle-text-size: root.detail-view-header-subtitle-text-size;
                        album-list-title-text-color: root.album-list-title-text-color;
                        album-list-subtitle-text-color: root.album-list-subtitle-text-color;
                        album-list-title-text-size: root.album-list-title-text-size;
                        album-list-subtitle-text-size: root.album-list-subtitle-text-size;
                        playlist: root.viewing-playlist;
                        play-playlist-clicked => { root.play-playlist-clicked() }
                        play-playlist-track-clicked(idx) => { root.play-playlist-track-clicked(idx) }
                    }

                if root.current-view == View.Playlists:
                    PlaylistsView {
                        bg-color: root.playlists-view-bg;
                        library-list-title-text-color: root.library-list-title-text-color;
                        library-list-subtitle-text-color: root.library-list-subtitle-text-color;
                        library-list-title-text-size: root.library-list-title-text-size;
                        library-list-subtitle-text-size: root.library-list-subtitle-text-size;
                        playlists: root.playlists;
                        playlist-opened(i) => {
                            root.current-view = View.OpenPlaylist;
                            root.viewing-playlist = root.playlists[i];
                            root.viewing-playlist-index = i;
                            root.playlist-opened(i);
                        }
                    }
            }
        }

        NowPlayingBar {
            play-paused-clicked => { root.play-paused-clicked() }
            next-track-clicked => { root.next-track-clicked() }
            prev-track-clicked => { root.prev-track-clicked() }
            shuffle-clicked => { root.shuffle-clicked() }
            repeat-clicked => { root.repeat-clicked() }
            current-position: root.current-position;
            total-duration: root.total-duration;
            seek-requested(val) => { root.seek-requested(val) }
            current-track-title: root.current-track-title;
            current-artist: root.current-artist;
            volume-changed(vol) => { root.volume-changed(vol) }
            current-volume: root.current-volume;
            current-art: root.current-art;
            bg-color: root.now-playing-bar-bg;
            now-playing-song-text-color: root.now-playing-song-text-color;
            now-playing-artist-text-color: root.now-playing-artist-text-color;
            now-playing-song-text-size: root.now-playing-song-text-size;
            now-playing-artist-text-size: root.now-playing-artist-text-size;
        }
    }
}
