import { SlintPlaylist } from "types.slint";
import { Button, ListView } from "std-widgets.slint";

export component OpenPlaylistView {
    in property <SlintPlaylist> playlist;

    callback play-playlist-clicked;
    callback play-playlist-track-clicked(int);

    VerticalLayout {
        padding: 20px;
        spacing: 10px;

        HorizontalLayout {
            alignment: start;
            spacing: 10px;

            VerticalLayout {
                alignment: center;
                // todo: playlist art on here too
            }

            VerticalLayout {
                horizontal-stretch: 0;

                Text {
                    text: root.playlist.name;
                    font-size: 28px;
                    font-weight: 700;
                }
            }

            Button {
                text: "▶";
                width: 70px;
                height: 70px;
                clicked => {
                    root.play-playlist-clicked();
                }
            }
        }

        ListView {
            for entry[i] in root.playlist.tracks: TouchArea {
                height : 65px;
                Rectangle {
                    VerticalLayout {
                        spacing: 4px;
                        alignment: center;
                        Text {
                            text: entry.title;
                            font-size: 15px;
                        }
                        Text {
                            text: entry.artist;
                            font-size: 12px;
                        }
                    }
                }
                clicked => {
                    root.play-playlist-track-clicked(i);
                }
            }
        }
    }
}
