export component Sidebar {
    callback library-selected();
    callback playlists-selected();

    in property <color> bg-color;
    in property <color> sidebar-text-color;
    in property <int> sidebar-text-size;

    width: 150px;

    Rectangle {
        background: root.bg-color;

        VerticalLayout {
            padding: 15px;
            spacing: 8px;
            alignment: start;

            Rectangle {
                border-color: #dbe6ff;
                border-width: 1px;
                border-radius: 5px;
                height: 50px;

                TouchArea {
                    Text {
                        text: "Library";
                        font-size: sidebar-text-size * 1px;
                        color: root.sidebar-text-color;
                    }
                    clicked => { library-selected() }
                }
            }

            Rectangle {
                border-color: #dbe6ff;
                border-width: 1px;
                border-radius: 5px;
                height: 50px;

                TouchArea {
                    Text {
                        text: "Playlists";
                        font-size: sidebar-text-size * 1px;
                        color: root.sidebar-text-color;
                    }
                    clicked => { playlists-selected() }
                }
            }
        }
    }
}
