import { Button } from "std-widgets.slint";

export component TrackButtons {
    callback play-paused-clicked();
    callback next-track-clicked();
    callback prev-track-clicked();

    HorizontalLayout {
        spacing: 10px;

        Button {
            width: 40px;
            height: 40px;
            text: "⏮";
            clicked => {
                root.prev-track-clicked();
            }
        }

        Button {
            width: 40px;
            height: 40px;
            text: "▶";
            clicked => {
                root.play-paused-clicked();
            }
        }

        Button {
            width: 40px;
            height: 40px;
            text: "⏭";
            clicked => {
                root.next-track-clicked();
            }
        }
    }
}
