export component TrackPlayingInfo {
    in property <string> current-track-title: "No song playing";
    in property <string> current-artist: "---";

    VerticalLayout {
        min-width: 0;
        alignment: center;
        padding-top: 10px;
        padding-left: 10px;

        Text {
            text: root.current-track-title;
            color: #cdd6f4;
            font-size: 15px;
            horizontal-alignment: left;
            overflow: elide;
        }

        Text {
            text: root.current-artist;
            color: #cdd6f4;
            font-size: 12px;
            horizontal-alignment: left;
            overflow: elide;
        }
    }
}
