import { SlintAlbum, SlintSong } from "../types.slint";
import { Button, ListView } from "std-widgets.slint";
import { DetailViewHeader } from "detail_view_header.slint";

export component AlbumView {
    in property <SlintAlbum> album;
    in property <color> bg-color;

    callback play-album-clicked;
    callback play-track-clicked(int);

    in property <color> detail-view-header-title-text-color;
    in property <color> detail-view-header-subtitle-text-color;
    in property <int> detail-view-header-title-text-size;
    in property <int> detail-view-header-subtitle-text-size;
    in property <color> album-list-title-text-color;
    in property <color> album-list-subtitle-text-color;
    in property <int> album-list-title-text-size;
    in property <int> album-list-subtitle-text-size;

    Rectangle {
    background: root.bg-color;

        VerticalLayout {
            padding: 20px;
            spacing: 10px;

            DetailViewHeader {
                art: root.album.art;
                title: root.album.title;
                subtitle: root.album.artist;
                detail-view-header-title-text-color: root.detail-view-header-title-text-color;
                detail-view-header-subtitle-text-color: root.detail-view-header-subtitle-text-color;
                detail-view-header-title-text-size: root.detail-view-header-title-text-size;
                detail-view-header-subtitle-text-size: root.detail-view-header-subtitle-text-size;
                play-clicked => { root.play-album-clicked() }
            }

            ListView {
                for entry[i] in root.album.tracks: TouchArea {
                    height: 65px;
                    Rectangle {
                        VerticalLayout {
                            spacing: 4px;
                            alignment: center;
                            Text { 
                                text: entry.title;
                                font-size: root.album-list-title-text-size * 1px;
                                color: root.album-list-title-text-color;
                            }
                            Text { 
                                text: entry.artist;
                                font-size: root.album-list-subtitle-text-size * 1px;
                                color: root.album-list-subtitle-text-color;
                            }
                        }
                    }
                    clicked => {
                        root.play-track-clicked(i);
                    }   
                }
            }
        }
    }
}
