import { Button } from "std-widgets.slint";

export component DetailViewHeader {
    in property <image> art;
    in property <string> title;
    in property <string> subtitle;

    in property <color> detail-view-header-title-text-color;
    in property <color> detail-view-header-subtitle-text-color;

    callback play-clicked();

    HorizontalLayout {
        alignment: start;
        spacing: 10px;

        VerticalLayout {
            alignment: center;
            Image {
                source: root.art;
                width: 80px;
                height: 80px;
            }
        }

        VerticalLayout {
            horizontal-stretch: 0;

            Text {
                text: root.title;
                font-size: 28px;
                font-weight: 700;
                color: detail-view-header-title-text-color;
            }

            Text {
                text: root.subtitle;
                font-size: 18px;
                color: detail-view-header-subtitle-text-color;
            }
        }

        Button {
            text: "▶";
            width: 70px;
            height: 70px;
            clicked => { root.play-clicked(); }
        }
    }
}
