export component EntryRow {
    in property <image> thumbnail;
    in property <string> title;
    in property <string> subtitle;

    callback entry-clicked();

    height: 65px;

    TouchArea {
        Rectangle {
            HorizontalLayout {
                padding-left: 20px;
                spacing: 10px;

                VerticalLayout {
                    alignment: center;
                    Image {
                        source: root.thumbnail;
                        width: 40px;
                        height: 40px;
                    }
                }

                VerticalLayout {
                    spacing: 4px;
                    alignment: center;
                    Text {
                        text: root.title;
                        font-size: 15px;
                    }
                    Text {
                        text: root.subtitle;
                        font-size: 12px;
                    }
                }
            }
        }
        clicked => { entry-clicked() }
    }
}
