import { ListView } from "std-widgets.slint";
import { SlintAlbum } from "../types.slint";
import { EntryRow } from "entry_row.slint";

export component LibraryView {
    in property <[SlintAlbum]> albums: [];
    in property <color> bg-color;
    callback album-opened(int);

    in property <color> library-list-title-text-color;
    in property <color> library-list-subtitle-text-color;

    Rectangle {
        background: root.bg-color;
        ListView {
            for entry[i] in root.albums: EntryRow {
                thumbnail: entry.art;
                title: entry.title;
                subtitle: entry.artist;
                entry-clicked => { root.album-opened(i) }
                library-list-title-text-color: root.library-list-title-text-color;
                library-list-subtitle-text-color: root.library-list-subtitle-text-color;
            }
        }
    }
}
