import { SlintPlaylist } from "../types.slint";
import { Button, ListView, StandardButton } from "std-widgets.slint";
import { DetailViewHeader } from "detail_view_header.slint";

export component OpenPlaylistView {
    in property <SlintPlaylist> playlist;
    in property <color> bg-color;

    in property <color> detail-view-header-title-text-color;
    in property <color> detail-view-header-subtitle-text-color;
    in property <color> album-list-title-text-color;
    in property <color> album-list-subtitle-text-color;

    callback play-playlist-clicked;
    callback play-playlist-track-clicked(int);

    Rectangle {
        background: root.bg-color;
        VerticalLayout {
            padding: 20px;
            spacing: 10px;

            DetailViewHeader {
                art: root.playlist.art;
                title: root.playlist.name;
                subtitle: "TRACK_COUNT tracks";
                detail-view-header-title-text-color: root.detail-view-header-title-text-color;
                detail-view-header-subtitle-text-color: root.detail-view-header-subtitle-text-color;
                play-clicked => { root.play-playlist-clicked() }
            }

            ListView {
                for entry[i] in root.playlist.tracks: TouchArea {
                    height : 65px;
                    Rectangle {
                        HorizontalLayout {
                            spacing: 10px;
                            VerticalLayout {
                                alignment: center;
                                Image {
                                    source: entry.art;
                                    width: 40px;
                                    height: 40px;
                                }
                            }
                            VerticalLayout {
                                spacing: 4px;
                                alignment: center;
                                Text {
                                    text: entry.title;
                                    font-size: 15px;
                                    color: root.album-list-title-text-color;
                                }
                                Text {
                                    text: entry.artist;
                                    font-size: 12px;
                                    color: root.album-list-subtitle-text-color;
                                }
                            }
                        }
                    }
                    clicked => {
                        root.play-playlist-track-clicked(i);
                    }
                }
            }
        }
    }
}
