import { ListView } from "std-widgets.slint";
import { SlintPlaylist } from "../types.slint";
import { EntryRow } from "entry_row.slint";

export component PlaylistsView {
    in property <[SlintPlaylist]> playlists: [];
    in property <color> bg-color;
    callback playlist-opened(int);

    Rectangle {
        background: root.bg-color;
        ListView {
            for entry[i] in root.playlists: EntryRow {
                thumbnail: entry.art;
                title: entry.name;
                subtitle: "TRACK_COUNT tracks";
                entry-clicked => { root.playlist-opened(i) }
            }
        }
    }
}
