music_dir = "~/Music"

sidebar_bg = "#0e101d"
now_playing_bar_bg = "#0a0a0f"
library_view_bg = "#1f1d2f"
album_view_bg = "#1f1d2f"
playlists_view_bg = "#1f1d2f"
open_playlist_view_bg = "#1f1d2f"

now_playing_song_text_color = "#cdd6f4"
now_playing_artist_text_color = "#cdd6f4"
detail_view_header_title_text_color = "#cdd6f4"
detail_view_header_subtitle_text_color = "#cdd6f4"
library_list_title_text_color = "#cdd6f4"
library_list_subtitle_text_color = "#cdd6f4"
album_list_title_text_color = "#cdd6f4"
album_list_subtitle_text_color = "#cdd6f4"
