---@class Keymaps
---@field toggle_play string?
---@field next_track string?
---@field prev_track string?
---@field volume_up string?
---@field volume_down string?
---@field seek_forward string?
---@field seek_backward string?
---@field open_library string?
---@field open_playlists string?

---@class Playlists
---@field name string
---@field songs string[]
---@field sort boolean?
---@field art string?

---@class OrpheusConfig
---@field music_dir string?
---@field default_volume number?
---@field window_maximized boolean?
---@field window_width number?
---@field window_height number?
---@field keymaps Keymaps?
---@field playlists Playlists[]?
---@field sidebar_bg string?
---@field now_playing_bar_bg string?
---@field library_view_bg string?
---@field album_view_bg string?
---@field playlists_view_bg string?
---@field open_playlist_view_bg string?
---@field sidebar_text_color string?
---@field now_playing_song_text_color string?
---@field now_playing_artist_text_color string?
---@field detail_view_header_title_text_color string?
---@field detail_view_header_subtitle_text_color string?
---@field library_list_title_text_color string?
---@field library_list_subtitle_text_color string?
---@field album_list_title_text_color string?
---@field album_list_subtitle_text_color string?
---@field sidebar_text_size number?
---@field now_playing_song_text_size number?
---@field now_playing_artist_text_size number?
---@field detail_view_header_title_text_size number?
---@field detail_view_header_subtitle_text_size number?
---@field library_list_title_text_size number?
---@field library_list_subtitle_text_size number?
---@field album_list_title_text_size number?
---@field album_list_subtitle_text_size number?
