import { Button } from "std-widgets.slint";
import { IconButton } from "../widgets/icon_button.slint";

export component DetailViewHeader {
    in property <image> art;
    in property <string> title;
    in property <string> subtitle;

    in property <color> detail-view-header-title-text-color;
    in property <color> detail-view-header-subtitle-text-color;
    in property <int> detail-view-header-title-text-size;
    in property <int> detail-view-header-subtitle-text-size;

    callback play-clicked();

    HorizontalLayout {
        alignment: start;
        spacing: 35px;

        VerticalLayout {
            alignment: center;
            Image {
                source: root.art;
                width: 80px;
                height: 80px;
            }
        }

        VerticalLayout {
            horizontal-stretch: 0;

            Text {
                text: root.title;
                font-size: root.detail-view-header-title-text-size * 1px;
                font-weight: 700;
                color: detail-view-header-title-text-color;
            }

            Text {
                text: root.subtitle;
                font-size: root.detail-view-header-subtitle-text-size * 1px;
                color: detail-view-header-subtitle-text-color;
            }
        }

        IconButton {
            icon-image: @image-url("../../../assets/icons/play.png");
            button-size: 70px;
            icon-size: 32px;
            
            clicked => {
                root.play-clicked();
            }
        }
    }
}
