import { ListView } from "std-widgets.slint";
import { SlintPlaylist } from "../types.slint";
import { EntryRow } from "entry_row.slint";

export component PlaylistsView {
    in property <[SlintPlaylist]> playlists: [];
    in property <color> bg-color;
    callback playlist-opened(int);

    in property <color> library-list-title-text-color;
    in property <color> library-list-subtitle-text-color;
    in property <int> library-list-title-text-size;
    in property <int> library-list-subtitle-text-size;

    Rectangle {
        background: root.bg-color;
        ListView {
            for entry[i] in root.playlists: EntryRow {
                thumbnail: entry.art;
                title: entry.name;
                subtitle: "TRACK_COUNT tracks";
                entry-clicked => { root.playlist-opened(i) }
                library-list-title-text-color: root.library-list-title-text-color;
                library-list-subtitle-text-color: root.library-list-subtitle-text-color;
                library-list-title-text-size: root.library-list-title-text-size;
                library-list-subtitle-text-size: root.library-list-subtitle-text-size;
            }
        }
    }
}
