[package]
name = "orpheus-desktop"
version.workspace = true
edition.workspace = true
build = "build.rs"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
enum_glob_use = "allow"

[dependencies]
orpheus-core = { path = "../core" }
async-executor = "1.14.0"
futures-lite = "2.6.1"
mpris-server = "0.10.0"
slint = "1.17.0"
tokio = { version = "1.52.3", features = ["full"] }

[build-dependencies]
slint-build = "1.17.0"
